name: "Build Docker Image"

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Get short SHA
        id: shortsha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: gitinsky
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gitinsky/dockerless-forgejo-runner:latest,gitinsky/dockerless-forgejo-runner:${{ steps.shortsha.outputs.sha }}
